{% set name = "gcs-oauth2-boto-plugin" %}
{% set version = "3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 748e8f73161c884bc1251748b4920115201829ed9a258e7112e8bf8ce45eae18

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - google-auth ==2.39.0
    - google-auth-httplib2 >=0.2.0
    - boto >=2.29.1
    - google-reauth >=0.1.0
    - httplib2 >=0.18
    - oauth2client >=2.2.0
    - pyopenssl >=0.13
    - python >={{ python_min }},<3.12
    - retry_decorator >=1.0.0
    - rsa ==4.7.2
    - six >=1.12.0

test:
  imports:
    - gcs_oauth2_boto_plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/gcs-oauth2-boto-plugin/
  summary: Auth plugin allowing use the use of OAuth 2.0 credentials for Google Cloud Storage in the Boto library.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
